/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jouvieje_bass_BassJNI */

#ifndef _Included_org_jouvieje_bass_BassJNI
#define _Included_org_jouvieje_bass_BassJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_SetConfig
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1SetConfig
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_GetConfig
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1GetConfig
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_SetConfigPtr
 * Signature: (IJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1SetConfigPtr
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_GetConfigPtr
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1GetConfigPtr
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_GetVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1GetVersion
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ErrorGetCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ErrorGetCode
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_GetDeviceInfo
 * Signature: (IJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1GetDeviceInfo
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_Init
 * Signature: (IIIJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1Init
  (JNIEnv *, jclass, jint, jint, jint, jlong, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_SetDevice
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1SetDevice
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_GetDevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1GetDevice
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_Free
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1Free
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_GetDSoundObject
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1GetDSoundObject
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_GetInfo
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1GetInfo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_Update
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1Update
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_GetCPU
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1GetCPU
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_Start
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1Start
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_Stop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1Stop
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_Pause
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1Pause
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_SetVolume
 * Signature: (F)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1SetVolume
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_GetVolume
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1GetVolume
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_PluginLoad
 * Signature: ([BI)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1PluginLoad
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_PluginFree
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1PluginFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_PluginGetInfo
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1PluginGetInfo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_Set3DFactors
 * Signature: (FFF)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1Set3DFactors
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_Get3DFactors
 * Signature: (Ljava/nio/FloatBuffer;JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1Get3DFactors
  (JNIEnv *, jclass, jobject, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_Set3DPosition
 * Signature: (JJJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1Set3DPosition
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_Get3DPosition
 * Signature: (JJJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1Get3DPosition
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_Apply3D
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1Apply3D
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_SetEAXParameters
 * Signature: (IFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1SetEAXParameters
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_GetEAXParameters
 * Signature: (Ljava/nio/IntBuffer;JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1GetEAXParameters
  (JNIEnv *, jclass, jobject, jlong, jobject, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_MusicLoad
 * Signature: (ZJJIII)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1MusicLoad__ZJJIII
  (JNIEnv *, jclass, jboolean, jlong, jlong, jint, jint, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_MusicLoad
 * Signature: (Z[BJIII)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1MusicLoad__Z_3BJIII
  (JNIEnv *, jclass, jboolean, jbyteArray, jlong, jint, jint, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_MusicFree
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1MusicFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_SampleLoad
 * Signature: (ZJJIII)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1SampleLoad__ZJJIII
  (JNIEnv *, jclass, jboolean, jlong, jlong, jint, jint, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_SampleLoad
 * Signature: (Z[BJIII)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1SampleLoad__Z_3BJIII
  (JNIEnv *, jclass, jboolean, jbyteArray, jlong, jint, jint, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_SampleCreate
 * Signature: (IIIII)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1SampleCreate
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_SampleFree
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1SampleFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_SampleSetData
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1SampleSetData
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_SampleGetData
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1SampleGetData
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_SampleGetInfo
 * Signature: (JLjava/nio/IntBuffer;J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1SampleGetInfo
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_SampleSetInfo
 * Signature: (JLjava/nio/IntBuffer;J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1SampleSetInfo
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_SampleGetChannel
 * Signature: (JZ)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1SampleGetChannel
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_SampleGetChannels
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1SampleGetChannels
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_SampleStop
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1SampleStop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_StreamCreate
 * Signature: (IIIZJ)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1StreamCreate__IIIZJ
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_StreamCreate
 * Signature: (IIIIJ)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1StreamCreate__IIIIJ
  (JNIEnv *, jclass, jint, jint, jint, jint, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_StreamCreateFile
 * Signature: (ZLjava/nio/ByteBuffer;JJJI)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1StreamCreateFile__ZLjava_nio_ByteBuffer_2JJJI
  (JNIEnv *, jclass, jboolean, jobject, jlong, jlong, jlong, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_StreamCreateFile
 * Signature: (Z[BJJI)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1StreamCreateFile__Z_3BJJI
  (JNIEnv *, jclass, jboolean, jbyteArray, jlong, jlong, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_StreamCreateURL
 * Signature: ([BIIZJ)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1StreamCreateURL
  (JNIEnv *, jclass, jbyteArray, jint, jint, jboolean, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_StreamCreateFileUser
 * Signature: (IIJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1StreamCreateFileUser
  (JNIEnv *, jclass, jint, jint, jlong, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_StreamFree
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1StreamFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_StreamGetFilePosition
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1StreamGetFilePosition
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_StreamPutData
 * Signature: (JLjava/nio/ByteBuffer;JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1StreamPutData
  (JNIEnv *, jclass, jlong, jobject, jlong, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_StreamPutFileData
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1StreamPutFileData
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_RecordGetDeviceInfo
 * Signature: (IJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1RecordGetDeviceInfo
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_RecordInit
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1RecordInit
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_RecordSetDevice
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1RecordSetDevice
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_RecordGetDevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1RecordGetDevice
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_RecordFree
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1RecordFree
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_RecordGetInfo
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1RecordGetInfo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_RecordGetInputName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1RecordGetInputName
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_RecordSetInput
 * Signature: (IIF)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1RecordSetInput
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_RecordGetInput
 * Signature: (ILjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1RecordGetInput
  (JNIEnv *, jclass, jint, jobject, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_RecordStart
 * Signature: (IIIZJ)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1RecordStart
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelBytes2Seconds
 * Signature: (IJ)D
 */
JNIEXPORT jdouble JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelBytes2Seconds
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelSeconds2Bytes
 * Signature: (ID)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelSeconds2Bytes
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelGetDevice
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelGetDevice
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelSetDevice
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelSetDevice
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelIsActive
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelIsActive
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelGetInfo
 * Signature: (IJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelGetInfo
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelGetTags
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelGetTags
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelFlags
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelFlags
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelUpdate
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelUpdate
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelLock
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelLock
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelPlay
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelPlay
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelStop
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelStop
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelPause
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelPause
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelSetAttribute
 * Signature: (IIF)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelSetAttribute
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelGetAttribute
 * Signature: (IILjava/nio/FloatBuffer;J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelGetAttribute
  (JNIEnv *, jclass, jint, jint, jobject, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelSlideAttribute
 * Signature: (IIFI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelSlideAttribute
  (JNIEnv *, jclass, jint, jint, jfloat, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelIsSliding
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelIsSliding
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelSet3DAttributes
 * Signature: (IIFFIIF)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelSet3DAttributes
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jint, jint, jfloat);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelGet3DAttributes
 * Signature: (ILjava/nio/IntBuffer;JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;JLjava/nio/IntBuffer;JLjava/nio/IntBuffer;JLjava/nio/FloatBuffer;J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelGet3DAttributes
  (JNIEnv *, jclass, jint, jobject, jlong, jobject, jlong, jobject, jlong, jobject, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelSet3DPosition
 * Signature: (IJJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelSet3DPosition
  (JNIEnv *, jclass, jint, jlong, jlong, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelGet3DPosition
 * Signature: (IJJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelGet3DPosition
  (JNIEnv *, jclass, jint, jlong, jlong, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelGetLength
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelGetLength
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelSetPosition
 * Signature: (IJI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelSetPosition
  (JNIEnv *, jclass, jint, jlong, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelGetPosition
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelGetPosition
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelGetLevel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelGetLevel
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelGetData
 * Signature: (ILjava/nio/ByteBuffer;JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelGetData
  (JNIEnv *, jclass, jint, jobject, jlong, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelSetSync
 * Signature: (IIJZJ)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelSetSync
  (JNIEnv *, jclass, jint, jint, jlong, jboolean, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelRemoveSync
 * Signature: (IJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelRemoveSync
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelSetDSP
 * Signature: (IZJI)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelSetDSP
  (JNIEnv *, jclass, jint, jboolean, jlong, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelRemoveDSP
 * Signature: (IJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelRemoveDSP
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelSetLink
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelSetLink
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelRemoveLink
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelRemoveLink
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelSetFX
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelSetFX
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_ChannelRemoveFX
 * Signature: (IJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1ChannelRemoveFX
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_FXSetParameters
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1FXSetParameters
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_FXGetParameters
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1FXGetParameters
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_bass_BassJNI
 * Method:    Bass_BASS_FXReset
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_BassJNI_Bass_1BASS_1FXReset
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
