/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jouvieje_bass_structures_StructureJNI */

#ifndef _Included_org_jouvieje_bass_structures_StructureJNI
#define _Included_org_jouvieje_bass_structures_StructureJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    HCHANNEL_SIZEOF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_HCHANNEL_1SIZEOF
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    HCHANNEL_newArray
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_structures_StructureJNI_HCHANNEL_1newArray
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DEVICEINFO_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DEVICEINFO_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DEVICEINFO_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DEVICEINFO_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DEVICEINFO_get_name
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DEVICEINFO_1get_1name
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DEVICEINFO_set_name
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DEVICEINFO_1set_1name
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DEVICEINFO_get_driver
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DEVICEINFO_1get_1driver
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DEVICEINFO_set_driver
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DEVICEINFO_1set_1driver
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DEVICEINFO_get_flags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DEVICEINFO_1get_1flags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DEVICEINFO_set_flags
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DEVICEINFO_1set_1flags
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_INFO_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1INFO_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_INFO_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1INFO_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_INFO_get_flags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1INFO_1get_1flags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_INFO_set_flags
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1INFO_1set_1flags
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_INFO_get_hwsize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1INFO_1get_1hwsize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_INFO_set_hwsize
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1INFO_1set_1hwsize
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_INFO_get_hwfree
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1INFO_1get_1hwfree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_INFO_set_hwfree
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1INFO_1set_1hwfree
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_INFO_get_freesam
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1INFO_1get_1freesam
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_INFO_set_freesam
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1INFO_1set_1freesam
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_INFO_get_free3d
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1INFO_1get_1free3d
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_INFO_set_free3d
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1INFO_1set_1free3d
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_INFO_get_minrate
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1INFO_1get_1minrate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_INFO_set_minrate
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1INFO_1set_1minrate
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_INFO_get_maxrate
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1INFO_1get_1maxrate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_INFO_set_maxrate
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1INFO_1set_1maxrate
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_INFO_get_eax
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1INFO_1get_1eax
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_INFO_set_eax
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1INFO_1set_1eax
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_INFO_get_minbuf
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1INFO_1get_1minbuf
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_INFO_set_minbuf
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1INFO_1set_1minbuf
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_INFO_get_dsver
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1INFO_1get_1dsver
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_INFO_set_dsver
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1INFO_1set_1dsver
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_INFO_get_latency
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1INFO_1get_1latency
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_INFO_set_latency
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1INFO_1set_1latency
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_INFO_get_initflags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1INFO_1get_1initflags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_INFO_set_initflags
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1INFO_1set_1initflags
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_INFO_get_speakers
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1INFO_1get_1speakers
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_INFO_set_speakers
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1INFO_1set_1speakers
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_INFO_get_freq
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1INFO_1get_1freq
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_INFO_set_freq
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1INFO_1set_1freq
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_RECORDINFO_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1RECORDINFO_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_RECORDINFO_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1RECORDINFO_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_RECORDINFO_get_flags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1RECORDINFO_1get_1flags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_RECORDINFO_set_flags
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1RECORDINFO_1set_1flags
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_RECORDINFO_get_formats
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1RECORDINFO_1get_1formats
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_RECORDINFO_set_formats
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1RECORDINFO_1set_1formats
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_RECORDINFO_get_inputs
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1RECORDINFO_1get_1inputs
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_RECORDINFO_set_inputs
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1RECORDINFO_1set_1inputs
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_RECORDINFO_get_singlein
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1RECORDINFO_1get_1singlein
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_RECORDINFO_set_singlein
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1RECORDINFO_1set_1singlein
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_RECORDINFO_get_freq
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1RECORDINFO_1get_1freq
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_RECORDINFO_set_freq
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1RECORDINFO_1set_1freq
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_get_freq
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1freq
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_set_freq
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1freq
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_get_volume
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1volume
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_set_volume
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1volume
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_get_pan
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1pan
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_set_pan
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1pan
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_get_flags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1flags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_set_flags
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1flags
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_get_length
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1length
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_set_length
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1length
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_get_max
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1max
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_set_max
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1max
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_get_origres
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1origres
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_set_origres
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1origres
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_get_chans
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1chans
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_set_chans
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1chans
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_get_mingap
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1mingap
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_set_mingap
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1mingap
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_get_mode3d
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1mode3d
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_set_mode3d
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1mode3d
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_get_mindist
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1mindist
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_set_mindist
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1mindist
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_get_maxdist
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1maxdist
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_set_maxdist
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1maxdist
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_get_iangle
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1iangle
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_set_iangle
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1iangle
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_get_oangle
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1oangle
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_set_oangle
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1oangle
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_get_outvol
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1outvol
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_set_outvol
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1outvol
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_get_vam
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1vam
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_set_vam
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1vam
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_get_priority
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1priority
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_SAMPLE_set_priority
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1priority
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_CHANNELINFO_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1CHANNELINFO_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_CHANNELINFO_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1CHANNELINFO_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_CHANNELINFO_get_freq
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1CHANNELINFO_1get_1freq
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_CHANNELINFO_set_freq
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1CHANNELINFO_1set_1freq
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_CHANNELINFO_get_chans
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1CHANNELINFO_1get_1chans
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_CHANNELINFO_set_chans
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1CHANNELINFO_1set_1chans
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_CHANNELINFO_get_flags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1CHANNELINFO_1get_1flags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_CHANNELINFO_set_flags
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1CHANNELINFO_1set_1flags
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_CHANNELINFO_get_ctype
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1CHANNELINFO_1get_1ctype
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_CHANNELINFO_set_ctype
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1CHANNELINFO_1set_1ctype
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_CHANNELINFO_get_origres
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1CHANNELINFO_1get_1origres
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_CHANNELINFO_set_origres
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1CHANNELINFO_1set_1origres
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_CHANNELINFO_get_plugin
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1CHANNELINFO_1get_1plugin
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_CHANNELINFO_set_plugin
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1CHANNELINFO_1set_1plugin
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_CHANNELINFO_get_sample
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1CHANNELINFO_1get_1sample
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_CHANNELINFO_set_sample
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1CHANNELINFO_1set_1sample
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_CHANNELINFO_get_filename
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1CHANNELINFO_1get_1filename
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_CHANNELINFO_set_filename
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1CHANNELINFO_1set_1filename
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_PLUGINFORM_SIZEOF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1PLUGINFORM_1SIZEOF
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_PLUGINFORM_newArray
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1PLUGINFORM_1newArray
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_PLUGINFORM_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1PLUGINFORM_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_PLUGINFORM_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1PLUGINFORM_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_PLUGINFORM_get_ctype
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1PLUGINFORM_1get_1ctype
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_PLUGINFORM_set_ctype
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1PLUGINFORM_1set_1ctype
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_PLUGINFORM_get_name
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1PLUGINFORM_1get_1name
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_PLUGINFORM_set_name
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1PLUGINFORM_1set_1name
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_PLUGINFORM_get_exts
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1PLUGINFORM_1get_1exts
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_PLUGINFORM_set_exts
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1PLUGINFORM_1set_1exts
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_PLUGININFO_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1PLUGININFO_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_PLUGININFO_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1PLUGININFO_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_PLUGININFO_get_version
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1PLUGININFO_1get_1version
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_PLUGININFO_set_version
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1PLUGININFO_1set_1version
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_PLUGININFO_get_formatc
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1PLUGININFO_1get_1formatc
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_PLUGININFO_set_formatc
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1PLUGININFO_1set_1formatc
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_PLUGININFO_get_formats
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1PLUGININFO_1get_1formats
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_PLUGININFO_set_formats
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1PLUGININFO_1set_1formats
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_3DVECTOR_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_13DVECTOR_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_3DVECTOR_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_13DVECTOR_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_3DVECTOR_get_x
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_13DVECTOR_1get_1x
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_3DVECTOR_set_x
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_13DVECTOR_1set_1x
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_3DVECTOR_get_y
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_13DVECTOR_1get_1y
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_3DVECTOR_set_y
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_13DVECTOR_1set_1y
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_3DVECTOR_get_z
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_13DVECTOR_1get_1z
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_3DVECTOR_set_z
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_13DVECTOR_1set_1z
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_3DVECTOR_create
 * Signature: (FFF)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_13DVECTOR_1create
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_3DVECTOR_set_xyz
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_13DVECTOR_1set_1xyz__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_3DVECTOR_set_xyz
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_13DVECTOR_1set_1xyz__JFFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_FILEPROCS_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1FILEPROCS_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_FILEPROCS_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1FILEPROCS_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_FILEPROCS_set_close
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1FILEPROCS_1set_1close
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_FILEPROCS_set_length
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1FILEPROCS_1set_1length
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_FILEPROCS_set_read
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1FILEPROCS_1set_1read
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_FILEPROCS_set_seek
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1FILEPROCS_1set_1seek
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_ID3_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1ID3_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_ID3_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1ID3_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_ID3_get_id
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1ID3_1get_1id
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_ID3_set_id
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1ID3_1set_1id
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_ID3_get_title
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1ID3_1get_1title
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_ID3_set_title
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1ID3_1set_1title
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_ID3_get_artist
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1ID3_1get_1artist
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_ID3_set_artist
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1ID3_1set_1artist
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_ID3_get_album
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1ID3_1get_1album
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_ID3_set_album
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1ID3_1set_1album
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_ID3_get_year
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1ID3_1get_1year
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_ID3_set_year
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1ID3_1set_1year
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_ID3_get_comment
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1ID3_1get_1comment
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_ID3_set_comment
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1ID3_1set_1comment
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_ID3_get_genre
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1ID3_1get_1genre
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_ID3_set_genre
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1ID3_1set_1genre
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_BEXT_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1BEXT_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_BEXT_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1BEXT_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_BEXT_get_Description
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1BEXT_1get_1Description
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_BEXT_set_Description
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1BEXT_1set_1Description
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_BEXT_get_Originator
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1BEXT_1get_1Originator
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_BEXT_set_Originator
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1BEXT_1set_1Originator
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_BEXT_get_OriginatorReference
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1BEXT_1get_1OriginatorReference
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_BEXT_set_OriginatorReference
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1BEXT_1set_1OriginatorReference
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_BEXT_get_OriginationDate
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1BEXT_1get_1OriginationDate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_BEXT_set_OriginationDate
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1BEXT_1set_1OriginationDate
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_BEXT_get_OriginationTime
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1BEXT_1get_1OriginationTime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_BEXT_set_OriginationTime
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1BEXT_1set_1OriginationTime
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_BEXT_get_TimeReference
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1BEXT_1get_1TimeReference
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_BEXT_set_TimeReference
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1BEXT_1set_1TimeReference
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_BEXT_get_Version
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1BEXT_1get_1Version
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_BEXT_set_Version
 * Signature: (JS)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1BEXT_1set_1Version
  (JNIEnv *, jclass, jlong, jshort);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_BEXT_get_UMID
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1BEXT_1get_1UMID
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_BEXT_set_UMID
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1BEXT_1set_1UMID
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_BEXT_get_Reserved
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1BEXT_1get_1Reserved
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    TAG_BEXT_set_Reserved
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_TAG_1BEXT_1set_1Reserved
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_CHORUS_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1CHORUS_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_CHORUS_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1CHORUS_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_CHORUS_get_fWetDryMix
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1CHORUS_1get_1fWetDryMix
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_CHORUS_set_fWetDryMix
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1CHORUS_1set_1fWetDryMix
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_CHORUS_get_fDepth
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1CHORUS_1get_1fDepth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_CHORUS_set_fDepth
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1CHORUS_1set_1fDepth
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_CHORUS_get_fFeedback
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1CHORUS_1get_1fFeedback
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_CHORUS_set_fFeedback
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1CHORUS_1set_1fFeedback
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_CHORUS_get_fFrequency
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1CHORUS_1get_1fFrequency
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_CHORUS_set_fFrequency
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1CHORUS_1set_1fFrequency
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_CHORUS_get_lWaveform
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1CHORUS_1get_1lWaveform
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_CHORUS_set_lWaveform
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1CHORUS_1set_1lWaveform
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_CHORUS_get_fDelay
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1CHORUS_1get_1fDelay
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_CHORUS_set_fDelay
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1CHORUS_1set_1fDelay
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_CHORUS_get_lPhase
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1CHORUS_1get_1lPhase
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_CHORUS_set_lPhase
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1CHORUS_1set_1lPhase
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_COMPRESSOR_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1COMPRESSOR_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_COMPRESSOR_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1COMPRESSOR_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_COMPRESSOR_get_fGain
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1COMPRESSOR_1get_1fGain
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_COMPRESSOR_set_fGain
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1COMPRESSOR_1set_1fGain
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_COMPRESSOR_get_fAttack
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1COMPRESSOR_1get_1fAttack
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_COMPRESSOR_set_fAttack
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1COMPRESSOR_1set_1fAttack
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_COMPRESSOR_get_fRelease
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1COMPRESSOR_1get_1fRelease
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_COMPRESSOR_set_fRelease
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1COMPRESSOR_1set_1fRelease
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_COMPRESSOR_get_fThreshold
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1COMPRESSOR_1get_1fThreshold
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_COMPRESSOR_set_fThreshold
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1COMPRESSOR_1set_1fThreshold
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_COMPRESSOR_get_fRatio
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1COMPRESSOR_1get_1fRatio
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_COMPRESSOR_set_fRatio
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1COMPRESSOR_1set_1fRatio
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_COMPRESSOR_get_fPredelay
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1COMPRESSOR_1get_1fPredelay
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_COMPRESSOR_set_fPredelay
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1COMPRESSOR_1set_1fPredelay
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_DISTORTION_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1DISTORTION_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_DISTORTION_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1DISTORTION_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_DISTORTION_get_fGain
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1DISTORTION_1get_1fGain
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_DISTORTION_set_fGain
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1DISTORTION_1set_1fGain
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_DISTORTION_get_fEdge
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1DISTORTION_1get_1fEdge
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_DISTORTION_set_fEdge
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1DISTORTION_1set_1fEdge
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_DISTORTION_get_fPostEQCenterFrequency
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1DISTORTION_1get_1fPostEQCenterFrequency
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_DISTORTION_set_fPostEQCenterFrequency
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1DISTORTION_1set_1fPostEQCenterFrequency
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_DISTORTION_get_fPostEQBandwidth
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1DISTORTION_1get_1fPostEQBandwidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_DISTORTION_set_fPostEQBandwidth
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1DISTORTION_1set_1fPostEQBandwidth
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_DISTORTION_get_fPreLowpassCutoff
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1DISTORTION_1get_1fPreLowpassCutoff
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_DISTORTION_set_fPreLowpassCutoff
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1DISTORTION_1set_1fPreLowpassCutoff
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_ECHO_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1ECHO_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_ECHO_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1ECHO_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_ECHO_get_fWetDryMix
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1ECHO_1get_1fWetDryMix
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_ECHO_set_fWetDryMix
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1ECHO_1set_1fWetDryMix
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_ECHO_get_fFeedback
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1ECHO_1get_1fFeedback
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_ECHO_set_fFeedback
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1ECHO_1set_1fFeedback
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_ECHO_get_fLeftDelay
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1ECHO_1get_1fLeftDelay
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_ECHO_set_fLeftDelay
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1ECHO_1set_1fLeftDelay
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_ECHO_get_fRightDelay
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1ECHO_1get_1fRightDelay
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_ECHO_set_fRightDelay
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1ECHO_1set_1fRightDelay
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_ECHO_get_lPanDelay
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1ECHO_1get_1lPanDelay
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_ECHO_set_lPanDelay
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1ECHO_1set_1lPanDelay
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_FLANGER_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1FLANGER_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_FLANGER_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1FLANGER_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_FLANGER_get_fWetDryMix
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1FLANGER_1get_1fWetDryMix
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_FLANGER_set_fWetDryMix
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1FLANGER_1set_1fWetDryMix
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_FLANGER_get_fDepth
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1FLANGER_1get_1fDepth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_FLANGER_set_fDepth
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1FLANGER_1set_1fDepth
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_FLANGER_get_fFeedback
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1FLANGER_1get_1fFeedback
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_FLANGER_set_fFeedback
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1FLANGER_1set_1fFeedback
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_FLANGER_get_fFrequency
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1FLANGER_1get_1fFrequency
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_FLANGER_set_fFrequency
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1FLANGER_1set_1fFrequency
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_FLANGER_get_lWaveform
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1FLANGER_1get_1lWaveform
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_FLANGER_set_lWaveform
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1FLANGER_1set_1lWaveform
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_FLANGER_get_fDelay
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1FLANGER_1get_1fDelay
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_FLANGER_set_fDelay
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1FLANGER_1set_1fDelay
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_FLANGER_get_lPhase
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1FLANGER_1get_1lPhase
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_FLANGER_set_lPhase
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1FLANGER_1set_1lPhase
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_GARGLE_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1GARGLE_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_GARGLE_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1GARGLE_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_GARGLE_get_dwRateHz
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1GARGLE_1get_1dwRateHz
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_GARGLE_set_dwRateHz
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1GARGLE_1set_1dwRateHz
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_GARGLE_get_dwWaveShape
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1GARGLE_1get_1dwWaveShape
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_GARGLE_set_dwWaveShape
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1GARGLE_1set_1dwWaveShape
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_I3DL2REVERB_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1I3DL2REVERB_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_I3DL2REVERB_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1I3DL2REVERB_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_I3DL2REVERB_get_lRoom
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1I3DL2REVERB_1get_1lRoom
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_I3DL2REVERB_set_lRoom
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1I3DL2REVERB_1set_1lRoom
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_I3DL2REVERB_get_lRoomHF
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1I3DL2REVERB_1get_1lRoomHF
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_I3DL2REVERB_set_lRoomHF
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1I3DL2REVERB_1set_1lRoomHF
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_I3DL2REVERB_get_flRoomRolloffFactor
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1I3DL2REVERB_1get_1flRoomRolloffFactor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_I3DL2REVERB_set_flRoomRolloffFactor
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1I3DL2REVERB_1set_1flRoomRolloffFactor
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_I3DL2REVERB_get_flDecayTime
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1I3DL2REVERB_1get_1flDecayTime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_I3DL2REVERB_set_flDecayTime
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1I3DL2REVERB_1set_1flDecayTime
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_I3DL2REVERB_get_flDecayHFRatio
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1I3DL2REVERB_1get_1flDecayHFRatio
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_I3DL2REVERB_set_flDecayHFRatio
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1I3DL2REVERB_1set_1flDecayHFRatio
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_I3DL2REVERB_get_lReflections
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1I3DL2REVERB_1get_1lReflections
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_I3DL2REVERB_set_lReflections
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1I3DL2REVERB_1set_1lReflections
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_I3DL2REVERB_get_flReflectionsDelay
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1I3DL2REVERB_1get_1flReflectionsDelay
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_I3DL2REVERB_set_flReflectionsDelay
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1I3DL2REVERB_1set_1flReflectionsDelay
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_I3DL2REVERB_get_lReverb
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1I3DL2REVERB_1get_1lReverb
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_I3DL2REVERB_set_lReverb
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1I3DL2REVERB_1set_1lReverb
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_I3DL2REVERB_get_flReverbDelay
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1I3DL2REVERB_1get_1flReverbDelay
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_I3DL2REVERB_set_flReverbDelay
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1I3DL2REVERB_1set_1flReverbDelay
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_I3DL2REVERB_get_flDiffusion
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1I3DL2REVERB_1get_1flDiffusion
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_I3DL2REVERB_set_flDiffusion
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1I3DL2REVERB_1set_1flDiffusion
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_I3DL2REVERB_get_flDensity
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1I3DL2REVERB_1get_1flDensity
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_I3DL2REVERB_set_flDensity
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1I3DL2REVERB_1set_1flDensity
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_I3DL2REVERB_get_flHFReference
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1I3DL2REVERB_1get_1flHFReference
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_I3DL2REVERB_set_flHFReference
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1I3DL2REVERB_1set_1flHFReference
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_PARAMEQ_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1PARAMEQ_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_PARAMEQ_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1PARAMEQ_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_PARAMEQ_get_fCenter
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1PARAMEQ_1get_1fCenter
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_PARAMEQ_set_fCenter
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1PARAMEQ_1set_1fCenter
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_PARAMEQ_get_fBandwidth
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1PARAMEQ_1get_1fBandwidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_PARAMEQ_set_fBandwidth
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1PARAMEQ_1set_1fBandwidth
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_PARAMEQ_get_fGain
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1PARAMEQ_1get_1fGain
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_PARAMEQ_set_fGain
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1PARAMEQ_1set_1fGain
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_REVERB_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1REVERB_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_REVERB_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1REVERB_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_REVERB_get_fInGain
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1REVERB_1get_1fInGain
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_REVERB_set_fInGain
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1REVERB_1set_1fInGain
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_REVERB_get_fReverbMix
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1REVERB_1get_1fReverbMix
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_REVERB_set_fReverbMix
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1REVERB_1set_1fReverbMix
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_REVERB_get_fReverbTime
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1REVERB_1get_1fReverbTime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_REVERB_set_fReverbTime
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1REVERB_1set_1fReverbTime
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_REVERB_get_fHighFreqRTRatio
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1REVERB_1get_1fHighFreqRTRatio
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_bass_structures_StructureJNI
 * Method:    BASS_DX8_REVERB_set_fHighFreqRTRatio
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_bass_structures_StructureJNI_BASS_1DX8_1REVERB_1set_1fHighFreqRTRatio
  (JNIEnv *, jclass, jlong, jfloat);

#ifdef __cplusplus
}
#endif
#endif
