/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jouvieje_bass_defines_DefineJNI */

#ifndef _Included_org_jouvieje_bass_defines_DefineJNI
#define _Included_org_jouvieje_bass_defines_DefineJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jouvieje_bass_defines_DefineJNI
 * Method:    get_BASSVERSION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_defines_DefineJNI_get_1BASSVERSION
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_defines_DefineJNI
 * Method:    get_NATIVEBASS_VERSION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_defines_DefineJNI_get_1NATIVEBASS_1VERSION
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
