/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jouvieje_bass_enumerations_EnumerationJNI */

#ifndef _Included_org_jouvieje_bass_enumerations_EnumerationJNI
#define _Included_org_jouvieje_bass_enumerations_EnumerationJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_GENERIC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1GENERIC
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_PADDEDCELL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1PADDEDCELL
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_ROOM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1ROOM
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_BATHROOM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1BATHROOM
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_LIVINGROOM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1LIVINGROOM
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_STONEROOM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1STONEROOM
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_AUDITORIUM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1AUDITORIUM
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_CONCERTHALL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1CONCERTHALL
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_CAVE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1CAVE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_ARENA
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1ARENA
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_HANGAR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1HANGAR
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_CARPETEDHALLWAY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1CARPETEDHALLWAY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_HALLWAY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1HALLWAY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_STONECORRIDOR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1STONECORRIDOR
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_ALLEY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1ALLEY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_FOREST
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1FOREST
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_CITY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1CITY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_MOUNTAINS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1MOUNTAINS
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_QUARRY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1QUARRY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_PLAIN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1PLAIN
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_PARKINGLOT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1PARKINGLOT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_SEWERPIPE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1SEWERPIPE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_UNDERWATER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1UNDERWATER
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_DRUGGED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1DRUGGED
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_DIZZY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1DIZZY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_PSYCHOTIC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1PSYCHOTIC
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_COUNT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1COUNT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_DX8_CHORUS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1DX8_1CHORUS
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_DX8_COMPRESSOR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1DX8_1COMPRESSOR
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_DX8_DISTORTION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1DX8_1DISTORTION
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_DX8_ECHO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1DX8_1ECHO
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_DX8_FLANGER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1DX8_1FLANGER
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_DX8_GARGLE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1DX8_1GARGLE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_DX8_I3DL2REVERB
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1DX8_1I3DL2REVERB
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_DX8_PARAMEQ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1DX8_1PARAMEQ
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_DX8_REVERB
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1DX8_1REVERB
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
